server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.123.132:3306/com.eliyax.ccat?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT+8
    username: root
    password: root
      # 如果不想配置对数据库连接池做特殊配置的话,以下关于连接池的配置就不是必须的
      # spring-boot 2.X 默认采用高性能的 Hikari 作为连接池 更多配置可以参考 https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 池中维护的最小空闲连接数
      minimum-idle: 5
      # 池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 20
      # 此属性控制从池返回的连接的默认自动提交行为。默认为 true
      auto-commit: true
      # 允许最长空闲时间
      idle-timeout: 30000
      # 此属性表示连接池的用户定义名称，主要显示在日志记录和 JMX 管理控制台中，以标识池和池配置。 默认值：自动生成
      pool-name: ccat-hikari
      #此属性控制池中连接的最长生命周期，值 0 表示无限生命周期，默认 1800000 即 30 分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认 30 秒，即 30000
      connection-timeout: 30000
      # 连接测试 sql 这个地方需要根据数据库方言差异而配置 例如 oracle 就应该写成  select 1 from dual
      connection-test-query: SELECT 1


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml


ccat:
  jwt:
    token-header: Authorization #JWT存储的请求头
    secret: mall-admin-secret #JWT加解密使用的密钥
    expiration: 604800 #JWT的超期限时间(60*60*24*7)
    token-prefix: 'Bearer '  #JWT负载中拿到开头
